### ISSUE TITLE
Allow graphqlEndpoint to Be set as a runtime environment variable

### ISSUE THREAD

**Issue by asonnleitner** [dulnan/nuxt-graphql-middleware#14]
The `graphqlEndpoint` option would be more useful as a runtime environment variable rather than a build-time variable. Currently, it's not possible to pass an empty string (`''`) during build, even when a `schema.graphql` file is present.

**Comment by luksak** [comment]
What is the solution to this? I'm struggling to set the endpoint based on an env variable as well.

**Comment by luksak** [comment]
You can do this: 

```
export default defineNuxtConfig({
  graphqlMiddleware: {
    graphqlEndpoint: process.env.API_URL,
  },
})
```

**Comment by memic84** [comment]
Thank you both @dulnan @luksak 

`NUXT_GRAPHQL_MIDDLEWARE_GRAPHQL_ENDPOINT ` didn't work for me, but setting process.env did.
