### ISSUE TITLE
[Warning]  Nuxt read error

### ISSUE THREAD

**Issue by suchkovcode** [dulnan/nuxt-graphql-middleware#20]
dependencies: 
![code](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/77999f13-4907-4504-af9b-365102b299c8)

config:
![code](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/47879b22-3159-4d94-8d25-5a360544a6c8)

error:
![hero](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/89f5d22b-a8fc-4d01-b359-d4870c0dc545)

I have a problem when starting the module. All settings were made according to the instructions, but when running in development mode it gives an error. Only the module is added to the code, there are no additional requests. I deleted the node_modules folder and look files, tried a new installation of modules and still the error remains, what could be the problem?

ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'nuxt')                                                                                            
  at graphqlMiddleware (node_modules/nuxt-graphql-middleware/dist/module.mjs:210:25)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3858:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:253:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:185:7)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev2.mjs:105:10)

**Comment by suchkovcode** [comment]
I found what the problem is. By default, npm/yarn downloads version 2.2.0. For nuxt 3, the current version is 4.0.0-beta.9; you also need to additionally download graphql as a dependency for nuxt-graphql-middleware to work.

Please fix the versioning of downloads from npm and separate the packages for version nuxt 2/3 separately, otherwise there will be errors when updating the package.

I also noticed that the package.json dependency versions in the repository are different from 4.0.0-beta.9. I assume that this is not the most current version of the package.

By correcting the package version and additionally installing graphql, I fixed the nuxt context error

**Comment by dulnan** [comment]
Yes indeed, the versions are messed currently. We are preparing a new release this week that will solve this. Sorry for the confusion!
