### ISSUE TITLE
[Question] No match found for location with path

### ISSUE THREAD

**Issue by suchkovcode** [dulnan/nuxt-graphql-middleware#21]
I just can’t figure out the reason for the lack of routers for graphql endpoints. I tried different options for setting up the config, but I still couldn’t find a working method. Schema all fields are received and types are generated correctly. I tested the request on postman and also got a response

![hero](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/40484b74-4b27-4402-8fb0-1c5cbbc9c2b2)

![code](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/81875803-ed5b-4319-a6e9-4f1fabb8471f)

![code](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/ec00ab3a-527c-4dc2-a682-d41b5752e615)

![code](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/1b1f776a-1345-456a-a658-515163f66101)

![hero](https://github.com/dulnan/nuxt-graphql-middleware/assets/105043724/58f571c0-51a2-4b9e-b586-ca5c523cf46e)

**Comment by yvrsky** [comment]
@suchkovcode Did you figure out the reason of problem?
