### ISSUE TITLE
Support for useAsyncGraphqlQuery

### ISSUE THREAD

**Issue by manuelmeister** [dulnan/nuxt-graphql-middleware#30]
I'd love to have a async variant ([useAsyncData](https://nuxt.com/docs/api/composables/use-async-data)) of the query and mutation function. I've tried to do this in my project, but the variables typing didn't work for me. Should I create a PR?

This would be similar to https://apollo.nuxtjs.org/getting-started/composables#useasyncquery and https://nuxt-graphql-client.web.app/getting-started/composables#useasyncgql

**Comment by dulnan** [comment]
This has been implemented and is available in the latest 4.1.0 release: https://nuxt-graphql-middleware.dulnan.net/composables/useAsyncGraphqlQuery.html
