### ISSUE TITLE
Query generation does not work for any version later than `3.1.0-beta.3`

### ISSUE THREAD

**Issue by madebyfabian** [dulnan/nuxt-graphql-middleware#36]
Hi there, I am almost certainly sure I missed something, if so, sorry! Just debugging this for a few hours now :D

I was updating a older project which was on `3.1.0-beta.3` and noticed that after updating to `4.1.0`, my queries in the `/pages` folder are no longer recognized, when I do `npm run dev`, the code generation table is just empty and the endpoints are gone.

I reproduced it in StackBlitz with an empty project. 
https://stackblitz.com/edit/github-rpys39-k1iu7q?file=package.json,pages%2Fcharacter.query.graphql
Installing `3.1.0-beta.3` works fine, but as soon as you upgrade the package to `3.1.0-beta.4` or latest `4.1.0` in `package.json` and then hit `npm run dev`, the generated query table in the console is empty and the endpoint is not available.

Tried it with several Nuxt versions and queries. Also with both `.gql` and `.graphql` ending. 

Am I missing something in the setup docs?

**Comment by dulnan** [comment]
You are probably missing the import pattern in the module config:

https://nuxt-graphql-middleware.dulnan.net/configuration/module.html#autoimportpatterns-string

but there is indeed an underlying bug: It should use a default pattern that would include all subfolders in the project root. But that default pattern is never actually applied. I will fix that. In the meantime, you could explicitly define the default pattern in your nuxt.config.ts:

https://github.com/dulnan/nuxt-graphql-middleware/blob/cd58ba63a2dbbf457bf82b37cffd98b3f39e2a01/src/module.ts#L239

**Comment by madebyfabian** [comment]
Thanks! Added that as a temporary fix.

**Comment by dulnan** [comment]
This has now been fixed in 4.1.1

**Comment by madebyfabian** [comment]
Thank you!
