### ISSUE TITLE
 Is it possible to use it with nuxt-multi-cache?

### ISSUE THREAD

**Issue by plcdnl** [dulnan/nuxt-graphql-middleware#39]
If yes, why here is not mentioned? 
https://nuxt-graphql-middleware.dulnan.net/features/caching.html

> Currently caching is not supported server side, but you can easily implement it yourself using the doGraphqlRequest server option method [...]

**Comment by timchesney** [comment]
There's a lengthy discussion with an example Gist at the end that uses nuxt-multi-cache etc here: #25 
Was just hunting around for that myself!
