### ISSUE TITLE
Should i add `outputPath` to `.gitignore`?

### ISSUE THREAD

**Issue by arthurfiorette** [dulnan/nuxt-graphql-middleware#4]

**Comment by dulnan** [comment]
Yes, you can add the folder to gitignore, because the resulting .graphql files written to outputPath are just the merged queries/mutations. They are not required for the module to work. It‘s more a way to debug queries and mutations.

**Comment by arthurfiorette** [comment]
thanks!

**Comment by arthurfiorette** [comment]
I just reopened it to ask if you can add this to the documentation

**Comment by dulnan** [comment]
Good point, will do!

**Comment by dulnan** [comment]
I will close this as with the upcoming V3 release the compiled queries aren't written to disk anymore outside of the .nuxt build folder.
