### ISSUE TITLE
Support GraphQL API endpoint served by Nuxt itself

### ISSUE THREAD

**Issue by lewebsimple** [dulnan/nuxt-graphql-middleware#49]
I have a Nuxt project with a GraphQL API endpoint at `/api/graphql` and I'd like to use this with `nuxt-graphql-middleware` but it doesn't seem to support a graphqlEndpoint pointing to `http://localhost:3000/api/graphql`, i.e. when the module starts the GraphQL endpoint is not ready so the codegen fails.

A possible workaround could be adding an option to specify the GraphQL schema file to use for codegen, instead of introspecting the provided graphqlEndpoint.

Maybe there are better / simpler ways of achieving this ?

Thanks !

**Comment by dulnan** [comment]
When you set `downloadSchema: false` in the config, the module will not attempt to download the schema but instead try to load it from the path defined in `schemaPath` which defaults to `~~/schema.graphql`. If you already have the GraphQL schema available in your repo you can point it there (it will not override the file unless `downloadSchema` is `true`).

**Comment by lewebsimple** [comment]
Hum, I did miss this option, thanks for the answer!

It works perfectly !
