### ISSUE TITLE
Better typescript queries inference with dts-dom

### ISSUE THREAD

**Issue by arthurfiorette** [dulnan/nuxt-graphql-middleware#5]
As many others typescript code generators, (and also `@graphql-codegen/[client plugins`), a complete typescript declaration is generated. Which includes knowing the parameters, and result types for all methods.

I saw that in [this file](https://github.com/dulnan/nuxt-graphql-middleware/blob/main/types/index.d.ts) you add a basic typescript declaration. The resulting methods are generated like so:

```ts
query(name: string, variables?: any, headers?: any): Promise<any>;
mutate(name: string, variables?: any, headers?: any): Promise<any>;
```

But, changing the type generation to this:

```ts
query<Q extends keyof Queries>(name: Q, variables: Queries[Q]['variables'], headers?: Record<string, string>): Promise<Queries[Q]['result']>;
// the same for mutate
```

And combining, with the help of [`dts-dom`](https://www.npmjs.com/package/dts-dom) or any similar package, you can programmatically generate:

```ts
// the graphql generated-operations file that, by default, goes into the types folder
import * as Gql from '../graphql-operations'

export type Queries = {
 articles: {
  variables: Gql.ArticleQueryVariables,
  result: GraphqlResult<Gql.ArticleQuery[]>
 }
}

// Interface GraphqlResult is the default `data` and `error` properties.

// The same above but for Mutations
export type Mutations = { }
```

Resulting into a complete typescript auto completion support:

_(Example of the variables parameter auto-completion)_

![image](https://user-images.githubusercontent.com/47537704/146694936-38ba9002-ea6b-48b7-a4af-e4054bff462f.png)

<br />

![image](https://user-images.githubusercontent.com/47537704/146695018-d7c5dab6-2769-4690-9369-304ef1b5cbcf.png)

Appearently, the only information that is needed to do the above is the operation name, if the operation is a query or a mutation (to divide between queries and mutations) and capitalize his name to auto-import from the `graphql-operations` generated file.

This feature will not have any changes to the javascript code, but it will create a 100% better coding experience and prevent many typescript preventable bugs.

**Comment by arthurfiorette** [comment]
I didn't have time to look at your source code, but if you can programmatically knows what is needed (and generated) by a query, like: This query has variables? if so, what are the generated typescript namings? You can avoid future naming conflict bugs and more.

**Comment by dulnan** [comment]
Both query variables and mutation inputs, query results and mutation results are generated as types (e.g. a query named Foobar will result in `FoobarQuery` and `FoobarVariables` being generated).

What I currently do in my projects is just manually providing the type, e.g.:

```
this.$graphql.query('foobar', (data: FoobarQuery) => {})
```

But inferring types based on query/mutation name would be much better indeed. I’ve thought about this before but didn‘t yet have time to look into it. I will definitely consider it though for one of the next releases!

**Comment by arthurfiorette** [comment]
In the next few weeks I'll have time to do a PR, as I don't think it would be much.

Could you show me where I could start? Like, what function would I know the name of queries and mutations and be able to generate code?

**Comment by dulnan** [comment]
The TS files are generated using [graphql-codegen](https://www.graphql-code-generator.com). The magic happens here:
https://github.com/dulnan/nuxt-graphql-middleware/blob/main/src/codegen.ts

The best option would probably be to create a custom plugin:
https://www.graphql-code-generator.com/docs/custom-codegen/write-your-plugin

Which doesn't seem too complex at first glance. The plugin could emit a custom `.d.ts` file that imports the already generated query and mutation types from `graphql-operations.ts` and defines the type aware `query()` and `mutate()` methods on the global `$graphql` object.

**Comment by dulnan** [comment]
With the upcoming V3 release of this module (which requires Nuxt 3) declaration files are generated to properly type arguments and return values for the query/mutation composables.

I did try adding this to the V2 release of this module, but ran into some issues I wasn't able to resolve without investing too much time into it.
