### ISSUE TITLE
Error [worker reload] [worker init] C:/Users/hey/Documents/project/.nuxt/dev/index.mjs on Windows

### ISSUE THREAD

**Issue by Applelo** [dulnan/nuxt-graphql-middleware#50]
Since the version 4.3.1, the plugin is throwing the error `ERROR  [worker reload] [worker init] C:/Users/hey/Documents/project/.nuxt/dev/index.mjs` on Windows.

I have launch the file `index.mjs` directly to find what is the cause, `graphql-documents` doesn't have the correct path
`import { documents } from 'C:/Users/hey/Documents/project/.nuxt/graphql-documents';`. 
This problem only happen on Windows, not on Linux or MacOS.

[EDIT]
Seems like, this is an issue coming from the new function `pathWithoutExtension` not working as expected on a Windows environement. I made a patch to return directly the path with the extension and it seems to work now 🤷‍♂️

**Comment by dulnan** [comment]
Confirmed it works in two large projects. Released it in 4.3.2
